openapi: "3.1.0"
info:
  title: "API Title"
  version: "1.0.0"
servers:
  - url: "http://localhost:3000/"
  - url: "http://safe-roadmap-prod-env.eba-56tfx8tr.ap-northeast-2.elasticbeanstalk.com/"
paths:
  /:
    get:
      responses:
        "200":
          description: "OK"
