openapi: "3.1.0"
info:
  title: "API Title"
  version: "1.0.0"
servers:
  - url: "http://localhost:3000/"
  - url: "http://safe-roadmap-prod-env.eba-56tfx8tr.ap-northeast-2.elasticbeanstalk.com/"
components:
  schemas:
    Error:
      type: object
      properties:
        success: 
          type: boolean
        message:
          type: string
  responses:
    successResponse:
        description: successful request with no data
        content:
          application/json:
            schema:
              type: object
              example: {"success": true, "message": "message", "result": "result"}
    BadRequest:
      description: 잘못된 요청
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          example: {"success": false, "message": "잘못된 요청"}
    InternalServerError:
      description: 서버 에러
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          example: {"success": false, "message": "서버 에러"}
#Paths api 경로 지정
paths:
  /pathfinding/pedestrain:
    $ref: './pathfinding.yaml#/~1pathfinding~1pedestrain'
  /pathfinding/transport:
    $ref: './pathfinding.yaml#/~1pathfinding~1transport'
  /arrival/bus:
    $ref: './arrival.yaml#/~1arrival~1bus'
  /arrival/subway:
    $ref: './arrival.yaml#/~1arrival~1subway'
  /photo/analysis:
    $ref: './photo.yaml#/~1photo~1analysis'
  /photo/report:
    $ref: './photo.yaml#/~1photo~1report'