openapi: 3.1.0
info:
  title: API Title
  version: 1.0.0
servers:
  - url: 'http://localhost:3000/'
  - url: 'http://safe-roadmap-prod-env.eba-56tfx8tr.ap-northeast-2.elasticbeanstalk.com/'
components:
  schemas:
    Error:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
  responses:
    successResponse:
      description: successful request with no data
      content:
        application/json:
          schema:
            type: object
            example:
              success: true
              message: message
              result: result
    BadRequest:
      description: 잘못된 요청
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            success: false
            message: 잘못된 요청
    InternalServerError:
      description: 서버 에러
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            success: false
            message: 서버 에러
paths:
  /pathfinding/pedestrain:
    get:
      tags:
        - Pathfinding
      summary: 도보 길 찾기 경로
      consumes: application/json
      responses:
        '200':
          $ref: '#/components/responses/successResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /pathfinding/transport:
    get:
      tags:
        - Pathfinding
      summary: 대중교통 길찾기 경로
      consumes: application/json
      responses:
        '200':
          $ref: '#/components/responses/successResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /arrival/bus:
    get:
      tags:
        - Arrival
      summary: 버스 도착 예정 시간
      consumes: application/json
      responses:
        '200':
          $ref: '#/components/responses/successResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /arrival/subway:
    get:
      tags:
        - Arrival
      summary: 지하철 도착 예정 시간
      consumes: application/json
      responses:
        '200':
          $ref: '#/components/responses/successResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /photo/analysis:
    post:
      tags:
        - Photo
      summary: 장애물&보도블록 파손 사진 분석
      consumes: application/json
      responses:
        '200':
          $ref: '#/components/responses/successResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /photo/report:
    post:
      tags:
        - Photo
      summary: 신고
      consumes: application/json
      responses:
        '200':
          $ref: '#/components/responses/successResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
