openapi: 3.1.0
info:
  title: API Title
  version: 1.0.0
servers:
  - url: 'http://localhost:3000/'
  - url: 'http://safe-roadmap-prod-env.eba-56tfx8tr.ap-northeast-2.elasticbeanstalk.com/'
components:
  schemas:
    Error:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
  responses:
    successResponse:
      description: successful request with no data
      content:
        application/json:
          schema:
            type: object
            example:
              success: true
              message: message
              result: result
    BadRequest:
      description: 잘못된 요청
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            success: false
            message: 잘못된 요청
    InternalServerError:
      description: 서버 에러
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            success: false
            message: 서버 에러
paths:
  /pathfinding/pedestrain:
    get:
      tags:
        - Pathfinding
      summary: 도보 길 찾기 경로
      consumes: application/json
      parameters:
        - in: query
          name: startX
          required: true
          schema:
            type: integer
            description: 출발지 X좌표
        - in: query
          name: startY
          required: true
          schema:
            type: integer
            description: 출발지 Y좌표
        - in: query
          name: endX
          required: true
          schema:
            type: integer
            description: 도착지 X좌표
        - in: query
          name: endY
          required: true
          schema:
            type: integer
            description: 도착지 Y좌표
        - in: query
          name: startName
          required: true
          schema:
            type: String
            description: 출발지 이름
        - in: query
          name: endName
          required: true
          schema:
            type: String
            description: 도착지 이름
        - in: query
          name: type
          required: true
          schema:
            type: integer
            description: 경로 타입
      responses:
        '200':
          $ref: '#/components/responses/successResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /pathfinding/transport:
    get:
      tags:
        - Pathfinding
      summary: 대중교통 길찾기 경로
      parameters:
        - in: query
          name: SX
          required: true
          schema:
            type: int
            description: 출발지 X좌표
        - in: query
          name: SY
          required: true
          schema:
            description: 출발지 Y좌표
        - in: query
          name: EX
          required: true
          schema:
            description: 도착지 X좌표
        - in: query
          name: EY
          required: true
          schema:
            description: 도착지 Y좌표
        - in: query
          name: type
          required: true
          schema:
            type: integer
            description: 경로 타입
      consumes: application/json
      responses:
        '200':
          $ref: '#/components/responses/successResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /arrival/bus:
    get:
      tags:
        - Arrival
      summary: 버스 도착 예정 시간
      parameters:
        - in: query
          name: stationId
          required: true
          schema:
            type: integer
            description: 버스 정류소 Id
        - in: query
          description: 정류소 이름
          name: stationName
          required: true
          schema:
            type: string
            description: 정류소 이름
        - in: query
          description: 버스 노선 Id
          name: busRouteId
          required: true
          schema:
            type: array
            description: 버스 노선 Id
      consumes: application/json
      responses:
        '200':
          $ref: '#/components/responses/successResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /arrival/subway:
    get:
      tags:
        - Arrival
      summary: 지하철 도착 예정 시간
      parameters:
        - in: query
          name: stationName
          required: true
          schema:
            type: String
            description: 지하철 이름
        - in: query
          name: subwayCode
          required: true
          schema:
            type: String
            description: 지하철 Code
        - in: query
          name: way
          required: true
          schema:
            type: Integer
            description: 지하철 way
      consumes: application/json
      responses:
        '200':
          $ref: '#/components/responses/successResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /photo/analysis:
    post:
      tags:
        - Photo
      summary: 장애물&보도블록 파손 사진 분석
      parameters:
        - in: query
          name: x
          required: true
          schema:
            type: Integer
            description: x좌표
        - in: query
          name: 'y'
          required: true
          schema:
            type: Integer
            description: y좌표
      consumes: application/json
      responses:
        '200':
          $ref: '#/components/responses/successResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /photo/report:
    post:
      tags:
        - Photo
      summary: 신고
      parameters:
        - in: body
          name: photoId
          required: true
          schema:
            type: Integer
            description: 사진의 아이디
      consumes: application/json
      responses:
        '200':
          $ref: '#/components/responses/successResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
